
meta_product_name: "KelX"
meta_title: "KelX - Fit by formula, dressed by data, styled by KelX."
meta_description: "Customised style and fit - mens fashion"
meta_image: "kelx-facebook.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
